project:
  type: book
  output-dir: docs

book:
  title: "Operational Time Series Forecasting"
  subtitle: "A Hands-On Guide to Classical and Modern Methods in R and Python"
  author: "Dominik Schulz"
  date: today
  date-format: long
  page-footer: "Copyright 2026, Dominik Schulz"
  chapters:
    - index.qmd
    - intro.qmd
    - part: part_preprocessing.qmd
      chapters:
        - randomvariables.qmd
    - part: part_modelfitting.qmd
      chapters:
        - randomvariables.qmd
    - part: part_modeltesting.qmd
      chapters:
        - summary.qmd
    - part: part_casestudies.qmd
      chapters:
        - summary.qmd
    - references.qmd
  appendices:
    - randomvariables.qmd

bibliography: references.bib
lang: en

format:
  html:
    theme: cosmo

editor: visual

